// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    CLAIMS: Queue;
    DB: D1Database
    WITHINGS_CLIENT_ID?: string
    WITHINGS_CLIENT_SECRET?: string
    MNEMONIC: string
    REWARDER_MNEMONIC_CHILD: string
    NETWORK: solo | main | test
    NODE_URL: string
}


interface QueueTask {
    method: string
    params: any[]
}

interface OAuthSession {
    state: string;
    user_id: string;
    service_id: string;
    service_user_id: string;
    access_token: string;
    refresh_token: string;
    expires_at: Date;
    created_at: Date;
    updated_at: Date;
}
