# This is an example configuration,
# you either configure all for your local deployment
# or empty it and manually configure everything in CloudFlare Pages Settings
#
# name = "x-earn-website"
# pages_build_output_dir = "./dist"
# compatibility_date = "2023-10-12"
# compatibility_flags = ["nodejs_compat_v2"]

# [vars]
# MNEMONIC = ""
# REWARDER_MNEMONIC_CHILD = "3"
# SIGNER_MNEMONIC = ""
# WITHINGS_CLIENT_ID = ""
# WITHINGS_SECRET = ""

# [[d1_databases]]
# binding = "DB"
# database_name = "db"
# database_id = ""
