name = "x-earn-website"
pages_build_output_dir = "./dist"
compatibility_date = "2023-10-12"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
SIGNER_MNEMONIC = "denial kitchen pet squirrel other broom bar gas better priority spoil cross"
